### ISSUE TITLE
Linking styleSheet

### ISSUE THREAD

**Issue by mp1pro** [willnaplesfl/prj-rev-bwfs-dasmoto#1]
The link to the stylesheet was broken, hence the web page did not have the correct styles. The link was `<link href="./resources/css/index.css" type="text/css" rel="stylesheet">`. However, there are no css or resources folder. It should be like this instead;

 <link href="./index.css" type="text/css" rel="stylesheet">

**Comment by willnaplesfl** [comment]
When I uploaded the folder, it uploaded the two files only and not the folder.  This surprised me and I appreciate your pointing out the problem.   

Everything worked okay in my testing for this issue but not the upload.  

I also put the project in my codepin account by copying/pasting the source, and that works correctly as you can see below if you wish.
https://codepen.io/Will_Johnson/live/JvXegL
