### ISSUE TITLE
header image

### ISSUE THREAD

**Issue by mp1pro** [willnaplesfl/prj-rev-bwfs-dasmoto#2]
Because the image was attached to the `header` class instead of `h1` the image took over all of the screen. instead of;

```
.header{
  background-image:
      url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align:center;
  font-size:100px;
  
  color:khaki;
}
```

use

```
h1{
  background-image:
      url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align:center;
  font-size:100px;
  
  color:khaki;
}
```

**Comment by willnaplesfl** [comment]
Thanks.  I made the change and it appears to work correctly now!  
The image looked large to me but I didn't recognize the error.

The change is at https://codepen.io/Will_Johnson/live/JvXegL also.
