### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [willnaplesfl/prj-rev-bwfs-dasmoto#3]
The structure of the design was implemented successfully. Only errors were in regards to linking the style sheet and displaying the main image. Everything else was spot on. Great job on the overall implementation and design.

**Comment by willnaplesfl** [comment]
Thank you for your thoughtful input and quick response!
I have a better understanding of the problems now that will help in the future.
Please let me know if I need to correct them for the certificate, which I hope to get.
If not, I prefer to keep moving ahead since I'm a little behind!

**Comment by mp1pro** [comment]
no need to resubmit. The project passed.
